### ISSUE TITLE
Add a way to stream the output of a command

### ISSUE THREAD

**Issue by maxux** [zero-os/0-core#115]
It would be interesting to have a command which stream the output of a command run in a container. When starting a command, there is no way to know the status (stdout, stderr) of that given command right now, until it complete.

**Comment by muhamadazmy** [comment]
I think i will close this one as `not happening any time soon` :)

**Comment by zaibon** [comment]
We'll need that now in order to be able to have a fast error detection in AYS.

Requirements:
- get output of a job from it's job id
- possibility to choose which stream we want to get (stdout, stderr)

**Comment by muhamadazmy** [comment]
Fixed by pull request #339
