### ISSUE TITLE
G8os client can't connect to packet machine after rebooting it

### ISSUE THREAD

**Issue by john-kheir** [zero-os/0-core#125]
![1](https://cloud.githubusercontent.com/assets/15011431/24691670/47f6d4d8-19d5-11e7-89ef-db7d087dec7f.png)
![3](https://cloud.githubusercontent.com/assets/15011431/24691754/acbb2950-19d5-11e7-8a6a-2813f28a3ce8.png)

**Comment by maxux** [comment]
Does the machine, before testing ?

**Comment by john-kheir** [comment]
client.bash('ls') --> returns nothing .. and of course it can't ping

**Comment by john-kheir** [comment]
## Tested on 1.1.0-alpha
**Before Rebooting**
```In [49]: client = g8core.Client('147.75.102.193')

In [50]: client.ping()
Out[50]: 'PONG Version: 1.1.0-alpha @Revision: b176c05b71e42bb995c39903f5fe0f0a212e460e'
```
**After Rebooting**
```
In [51]: client.ping()
```

**Comment by maxux** [comment]
What kind of reboot ? Using the packet.net reset or using the client reboot ?

**Comment by john-kheir** [comment]
using packet rebooting.

**Comment by john-kheir** [comment]
![rebootissue](https://cloud.githubusercontent.com/assets/15011431/25182636/96977476-2515-11e7-8057-bb5587e911be.png)

**Comment by muhamadazmy** [comment]
I think this should be reported to packet.net support team

**Comment by maxux** [comment]
Does anybody reported that to packet.net ?

**Comment by muhamadazmy** [comment]
I don't think so, @FastGeert can u take care of this? :)

**Comment by muhamadazmy** [comment]
won't fix

**Comment by maxux** [comment]
On the « Server » page on Packet.net portal, by choosing « Always Boot PXE » this fix the problem.
