### ISSUE TITLE
own console on G8OS

### ISSUE THREAD

**Issue by despiegk** [zero-os/0-core#172]
- create own console which allows user to (on the terminal)
- see status 
- ping to a remote host
- ?

**Comment by muhamadazmy** [comment]
@grimpy can u make sure you place the config you have to start `agetty` in core0 default config.

**Comment by grimpy** [comment]
Unassigning myself as this required more specifications and is due for next milestone

**Comment by grimpy** [comment]
bootscreen provides all info requested in this ticket,
