### ISSUE TITLE
client.kvm.remove_nic isn't working as expected

### ISSUE THREAD

**Issue by john-kheir** [zero-os/0-core#223]
# Scenario
**1- Create vm and list its info, no nics should be found**
```
In [240]: n6 = client.kvm.create(name='vm6', media=[{'url': '/var/cache/images/Ubuntu.14.04.x64.qcow2'}])

In [241]: n6
Out[241]: 
DATA:
"492efa80-c42b-45f0-b639-f46caaf98d7b"

In [242]: client.kvm.info('492efa80-c42b-45f0-b639-f46caaf98d7b')
Out[242]: 
{'Block': [{'Name': 'vda',
   'RdBytes': 58527232,
   'RdTimes': 4069368110,
   'WrBytes': 262144,
   'WrTimes': 66785433}],
 'Net': [],
 'Vcpu': [{'State': 1, 'Time': 16890000000}, {'State': 1, 'Time': 4680000000}]}
```
**2- Add nic of type "vlan" and id "403", it will take tap7 label when listing the vm info**
```
In [243]: client.kvm.add_nic('492efa80-c42b-45f0-b639-f46caaf98d7b', 'vlan', id='403')

In [244]: client.kvm.info('492efa80-c42b-45f0-b639-f46caaf98d7b')
Out[244]: 
{'Block': [{'Name': 'vda',
   'RdBytes': 61021696,
   'RdTimes': 4118148876,
   'WrBytes': 716800,
   'WrTimes': 90219550}],
 'Net': [{'Name': 'tap7',
   'RxBytes': 508,
   'RxDrop': 0,
   'RxErrs': 0,
   'RxPkts': 6,
   'TxBytes': 850,
   'TxDrop': 0,
   'TxErrs': 0,
   'TxPkts': 7}],
 'Vcpu': [{'State': 1, 'Time': 17830000000}, {'State': 1, 'Time': 5660000000}]}
```
**3- Remove the nic, should succeed**
```
In [245]: client.kvm.remove_nic('492efa80-c42b-45f0-b639-f46caaf98d7b', 'vlan', id='403')
---------------------------------------------------------------------------
RuntimeError: ('invalid response: ERROR', STATE: ERROR
STDOUT:

STDERR:

DATA:
"The nic you tried is not attached to the vm"
)
```
## Actual Result
This nic hasn't been removed claiming that the nic is not attached to the vm

## Expected Result
The nic should be removed 
## Note 
Please make sure same problem doesn't happen when adding vxlans and bridges as nics
## Version
1.1.0-alpha @Revision: cb9127069375fb32a5e03ac88ab71504212487aa

**Comment by john-kheir** [comment]
still not working as expected

**Comment by muhamadazmy** [comment]
Can't reproduce. If u can reproduce me please preserve the state of the machine for investigation

**Comment by john-kheir** [comment]
this issue still happens with the bridges

**Comment by mie00** [comment]
So the problem is, when removing nics, the vm has to have an operating system running, otherwise it doesn't work.
#324 makes sure that a virtual machine has to be started using a boot disk, but it is not enough, for example a boot disk without an os will result in the same problem.

**Comment by john-kheir** [comment]
Verified on master @Revision: b7862f0293626662a4e4d30efffceb9ee869fcb5
