### ISSUE TITLE
Wrong path on the documentation to run "initramfs" script

### ISSUE THREAD

**Issue by donatogomez** [zero-os/0-core#281]
Change directory command "cd" have the wrong path, need to be fix with the right one indicated on the second  #picture.

![image](https://cloud.githubusercontent.com/assets/14346541/26631454/554a72ea-460b-11e7-9c2d-1ddee5120e68.png)

The right one:
![image](https://cloud.githubusercontent.com/assets/14346541/26631626/4241b2de-460c-11e7-938c-0607cabe3dc2.png)

**Comment by zaibon** [comment]
@donatogomez  Where is this screenshot coming from ?

**Comment by donatogomez** [comment]
Sorry for the late answer@zaibon,
the first one is a screenshot of the documentation. 
https://github.com/zero-os/0-initramfs/blob/master/README.md

The second one is how I access to the script in my machine.

I'll fix it!

**Comment by muhamadazmy** [comment]
@donatogomez this issue should be moved to 0-initramfs repo, not 0-core

**Comment by zaibon** [comment]
moved to https://github.com/zero-os/0-initramfs/issues/46
