### ISSUE TITLE
security:LedisDB has a public access 

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-core#282]
**Steps**
- Install the latest OS
- try to do
```bash
redis-cli -h <ip>
```

**Actual result:**
You have a full access to the database and u can do any command like reading key, write key, dump data or even flushall db or shutdown it

![screenshot from 2017-05-31 14-15-06](https://cloud.githubusercontent.com/assets/17981089/26631551/d26d7362-460b-11e7-99a1-ab31eb24d408.png)

**Expected result**
LeidisDB shouldn't be exposed to public world

**Comment by muhamadazmy** [comment]
Security now is implemented on 3 levels:
- If `zerotier=<network-id>` is added to the kernel boot params, zero-os will only accept connection over this zerotier network (unless debug is set, then it will still accept connections from all interfaces)
- If `organization=<org-name>` is added to the kernel boot params, ledis will require authorization using an itsyouonline signed JWT token that has the role `user:memberOf:<org-name>` granted.
- Now, all ledis connection is over `ssl` (make sure u have latest client)

**Comment by john-kheir** [comment]
Verified on master @Revision: 807fa1939199fa3aa3b3e57679f61bb6c72cc57f
