### ISSUE TITLE
Remove the link on the bottom

### ISSUE THREAD

**Issue by donatogomez** [zero-os/0-core#283]
To be clear about "Ping G8OS" section, just remove the link at the bottom and add the information needed from the link into this documentation.
![image](https://cloud.githubusercontent.com/assets/14346541/26633886/2b575eee-4615-11e7-8694-997286ba28d3.png)

**Comment by yveskerwyn** [comment]
See: https://github.com/zero-os/0-core/commit/26aa658f7b941204fb7019d257c6b72d3d164f63
