### ISSUE TITLE
Add `ip` like instrumentation for nics on containers and core0

### ISSUE THREAD

**Issue by grimpy** [zero-os/0-core#285]
This is usefully for containers that dont have ip command in their flist

Minimum requirements, able to create bridges add/remove interfaces to bridges
Add/remove ipaddress/routes
Set interface up and down
List ips/routes

**Comment by delandtj** [comment]
So I still don't get why `ip` would be a problem to integrate in an flist

**Comment by muhamadazmy** [comment]
it's easier for developers to work against an API that has a strongly typed defined types than with a comman line tool. They also won't have to parse the output of the command line. which will make code much cleaner. 
core0 already uses netlink libraries to manage it's network, and exposed a subset of the ip command is not a big deal
