### ISSUE TITLE
On Mac: AttributeError: module 'socket' has no attribute 'TCP_KEEPIDLE'

### ISSUE THREAD

**Issue by yveskerwyn** [zero-os/0-core#290]
See:
![screen shot 2017-06-02 at 13 37 13](https://cloud.githubusercontent.com/assets/13795109/26724329/17d5fefe-4799-11e7-8e4c-c766293e0990.png)

**Comment by FastGeert** [comment]
I would only support it from the jsdocker for this release, so we can create a known issue for it.

**Comment by muhamadazmy** [comment]
@FastGeert should we remove the TCP_KEEPIDLE flag ?

**Comment by yveskerwyn** [comment]
it works now
