### ISSUE TITLE
Booting Zero-OS from USB doesn't work

### ISSUE THREAD

**Issue by yveskerwyn** [zero-os/0-core#312]
Following the instructions for this doesn't result in successful boot of Zero-OS: https://github.com/zero-os/0-core/blob/master/docs/booting/usb.md

We need to have this working for our EAP

@maxux can you check what we do wrong?

I've been testing it on multiple machines, and many of us have been involved...

**Comment by maxux** [comment]
Is this issue related to @donatogomez ?

**Comment by FastGeert** [comment]
Booting from usb works on other machines. @maxux pls validate the documentation

**Comment by zaibon** [comment]
fixed by https://github.com/zero-os/0-core/commit/b7862f0293626662a4e4d30efffceb9ee869fcb5#diff-18a76c5541c8e6d4793afbd8e4e5079b
