### ISSUE TITLE
nft integration clean up

### ISSUE THREAD

**Issue by muhamadazmy** [zero-os/0-core#317]
We need to find the best way to setup nft keeping in mind the following point:
1- Bridges uses nft to setup some natting and firewall rules that requires certain tables and chain to exist.
2- We only apply zerotier rules when `debug` is not set. with debug ledis and ssh accepts connections from all interface.
3- Initramfs image already have a basic nft config file that creates some tables and chains (no rules)

I suggest the following sequence
- core0 adds the required tables and chains for it's operation.
- core0 decide if to add zerotier rules (depending on flags) (also should be configurable - may be in core0 network config file {which ports to only allow over zt})
- core0 applys nftfilter rules from the config files last. to add any extra configuration

**Comment by muhamadazmy** [comment]
@maxux any thoughts ?

**Comment by maxux** [comment]
Looks good. I'll check if a better flow could be applied.
