### ISSUE TITLE
Persistent zerotier node-ids for core-0 & core-X

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-core#347]
@robvanmieghem did already some investigation on how we could make the zerotier node-ids persistent for core-0. See https://github.com/zero-os/0-orchestrator/issues/255#issuecomment-303040184

We can use the mac-address of the first interface in the node to create a seed for the private key generation.

Now we want this to work for containers as well, so that they also could get the same zerotier-ip after a reboot for example. To be able to achieve this, we'll need something to identify the container, so we'll have to give it a name. Then we can use the name in combination with the mac-address to create the seed for the private key for the core-X

**Comment by muhamadazmy** [comment]
For the name part, we can use the already existing tags.
