### ISSUE TITLE
node can't re-join zt network after restarting

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-core#377]
**steps**
- Create a node with the latest ipxe
https://bootstrap.gig.tech/ipxe/zero-os-master/{nw_id}
- Make sure that this node joined the zt nw and take an ip
- Restart this node
- Check the zt hosts 

**Actual result**
![image](https://user-images.githubusercontent.com/17981089/27907485-2230a290-6248-11e7-8563-bfad6b6e9644.png)

**Expected result**
Node should be able to re-join the zt nw

**Comment by muhamadazmy** [comment]
Can u validate that the machine actually booted after a reboot ? Packet.net had issue with rebooting machines when using IPXE.

To make sure of this, please make sure u have the ssh console connected and then reboot the machine.

**Comment by islamTaha12** [comment]
packet issue
