### ISSUE TITLE
Ays can't authorize new nodes 

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-core#379]
- Create new node with ipxe: 
 ``` https://bootstrap.gig.tech/ipxe/zero-os-master/{nwid}/organization={org_name}```
- Give this error :  
```
b job: node.zero-os!248a07e3cbf0 (monitor) done sucessfuly
[Thu06 13:29] - e50af62578c619ca229d6bf9156aa0a5.py:74  :j.core.jobcontroller.job.04c7bfadec147e7e79766670e66967e3 - INFO     - authorize new member 24208779a3
[Thu06 13:29] - e50af62578c619ca229d6bf9156aa0a5.py:25  :j.core.jobcontroller.job.04c7bfadec147e7e79766670e66967e3 - ERROR    - Could not connect to remote host 172.27.219.57
```
Although ays can authorize old node created this morning normally

**Comment by despiegk** [comment]
not clear to me what the issue is?
in ays? in zero-os?

**Comment by Dinaamagdy** [comment]
it was in jwt token generation but it solved now by https://github.com/Jumpscale/ays9/pull/98/files ,so we can close this issue now
