### ISSUE TITLE
Pub/Sub for logs

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-core#390]
## Concept: 
We would like to improve the logging mechanism present in 0-core
Currently, any process that output a certain format is considered a log and is catch by 0-core to be put into a ledis queue.
The improvement that we want to bring is to provide the possibility to subscribe to the log of a specific process (see https://github.com/zero-os/0-core/issues/388)

## Requirements:
- Possibility to subscribe to the log produce by any process/vm/container/...
- The logs should not be lost if the subscriber is not yet listening to the publication when the log is emited (with some limits, after a certain amount of logs we clean ledis to not explode memory)
- The subscriber need to be notify when a new log is available
  - this is done by 0-core that send a event to all subscriber with the location of the new log

## Implementation idea:
when a log entry is created by 0-core, logs is added to a hset and and notification is sent to all subscriber.
The notification is the location of the new log in the hset.
Some logic (can be lua script in ledis) that deal with cleaning log when memory limit is reach or if all subscriber have consumed the log

**Comment by zaibon** [comment]
This is going to be used by https://github.com/Jumpscale/ays9/issues/105 to monitor services

**Comment by muhamadazmy** [comment]
How is that different from the current output stream support ?

**Comment by zaibon** [comment]
This is different in multiple ways:
- Using the logging system, the logs are aggregated in redis
- The new pub/sub architecture allow to have multiple reader
- The new pub/sub architecture allow for someone to get the logs even if he start subscribe after the logs has been emitted. 
- ...

**Comment by muhamadazmy** [comment]
@zaibon 
By the way (answering your points in order)

- Streams uses logging, u get all messages of all log levels, the python client just prints the message in a "beautiful" way which looks like it's just the stdout/stderr
- Do we really need multiple listeners ?
- Streams does that by default, if u enabled streams u don't lose any of the logger messages.

**Comment by zaibon** [comment]
> Do we really need multiple listeners ?

Yes we do.

So is I read you correctly, the stream implementation already does all the rest ?
Then is even less work, very good !  :-)
