### ISSUE TITLE
Automatically start a binary from a flist on the node itself

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-core#396]
### Goal:
In order to be able to complete https://github.com/zero-os/0-orchestrator/issues/620
0-core should be able to automatically mount a flist and then start a processs from a binary present in the flist.
This process needs to be monitored by 0-core and automatically restarted if it stop/crashes.

This feature won't requires an public API since this kind of processes won't be started from a user but only managed by 0-core like a core service.

**Comment by muhamadazmy** [comment]
Not merged
