### ISSUE TITLE
core0 consumes a lot of memory over time

### ISSUE THREAD

**Issue by grimpy** [zero-os/0-core#450]
```
1     0 root     S    4220m106.3   0  4.3 /sbin/core0 -c /etc/zero-os/zero-o
```

**Comment by grimpy** [comment]
Proposed solution would be:

Provide a command in 0-core to move ledis database to disk.
This command will switch database backend from memory store to disk storage.

0-orchestrator will issue this command when the node is being boostrapped (or restarted) and point to the fscachedisk. at this point the client will need to reconnect. This is not really a problem as there will be no client connections yet as the node is still in bootstrap phase.

**Comment by zaibon** [comment]
Before moving ledis to disk, we'll first reduce the number of backlog message we keep per process.
We should also investigate and check if the aggregation of the statistics works properly.

**Comment by muhamadazmy** [comment]
Aggregation are fine, i moved the ledis to disk for debugging and after running spammy heavy processes the ledis db didn't increase that much (around 10M) 

I will reduce the number of backlog messages per job, and try again. I will also review that no other leaks happens somewhere else.

Also this became an issue around a week ago. So it might be related to some changes.

**Comment by islamTaha12** [comment]
![image](https://user-images.githubusercontent.com/17981089/29073646-ae48e530-7c4c-11e7-8b7a-802001474be2.png)
