### ISSUE TITLE
Zero-core stop processing command queue

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-core#462]
Logs of the node : https://drive.google.com/open?id=0B-WwI8L0vOqASGZFT1ZLWGdxMmc

**Comment by maxux** [comment]
We found out that commands in redis queue and not dequeued, but we don't know the reason.
Other parts of the core seems to works properly.

On this screenshot, we can see the following:
![screenshot](https://i.imgur.com/DRUxIql.jpg)

- The redis socket can be reached
- The tls handshake is well made
- The jwt authentification works
- When sending a command to the queue, id was more than 300

This is why I guess queue was frozen.

**Comment by muhamadazmy** [comment]
@maxux did u try to dequeue something from the queue with the client ?

**Comment by muhamadazmy** [comment]
I creates this gist to reproduce this issue https://gist.github.com/muhamadazmy/cfca4d37b111f6beb23925d2369b384c

I do exactly the same as what we do in core0
- We create the ledis app
- We start a go routine to pop commands out of ledis queue
- We connect via a redis client to push commands to queue

This gist, will connect and keep pushing random chunks of data to a ledis queue, after few seconds we see that the counter blocks and no more commands are poped out of the queue.
U still can use a normal redis-cli (cli or python) to check the length of the growing queue. Also u still can pop out the pushed data. only the go routine cannot

I will check ledis code to see if it's some bug we can fix.

**Comment by muhamadazmy** [comment]
This must be some race condition in ledis that causes this, but i managed to work around it by never do a BRpop of duration 0 (block indefinitely). By using a timeout, instead of 0 the loop managed to unblock. 

I will apply the fix on core0. And post an issue on ledis repo.

**Comment by muhamadazmy** [comment]
Ledis issue: https://github.com/siddontang/ledisdb/issues/314
