### ISSUE TITLE
Allow utility containers to access other containers filesystem

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-core#487]
First, what do I cal a utility container: Any container that is start automatically by 0-core in order to have access to tools that are not part of the initramfs. For example the openvswtich container is an utility container.

The idea behind this FR is to allow to have the tools contained in a utility containers access the filesystem of some other containers. 

A example use case would be for the creation of flist and sandboxing. We have quite some logic and tools in Jumpscale to perfom sandboxing. We cold imagine that the python client expose a method that allow to quickly create a flist from a part of a container filesystem. To do so 0-core would automatically boot a container with an jumpscale flist, then use the tools newly available to execute some actions on the container where we want to create the flist from.  
But for this to work, the utility container need to be able to have access to the filesystem of the other container.

This feature should still ensure security. only utility container managed by 0-core itself should be authorize to access other container filesystem. So we keep perfect isolation for end users.

**Comment by grimpy** [comment]
@muhamadazmy yes this could work in theory but I dont like how this causes dependencies for the containers.
@zaibon for your usecase I would prefer flist merging at runtime (by g8ufs), eg allow passing a list of flists...

**Comment by despiegk** [comment]
security should not be looked at, anyone accessing the zero-core api (redis) has all access anyhow
