### ISSUE TITLE
Watchdog: flooding node with 'logger.subscribe' calls

### ISSUE THREAD

**Issue by muhamadazmy** [zero-os/0-core#490]
Watchdog call to the node 'logger.subscribe' is going wild, if u change log level to `DEBUG` u can see thousands of calls to 'logger.subscribe'

**Comment by john-kheir** [comment]
## Verified on
 orch: alpha 8
 0core: master @Revision: 3ed57fc769bd3454579db5d5f692cf313a6734cf
