### ISSUE TITLE
Documentation not updated on the JWT usage for the clients

### ISSUE THREAD

**Issue by dinosn** [zero-os/0-core#495]
Hi, the documentation is not updated for the correct usage of the client. 

Eg. on the current documentation the python client can ping a node by using
```
>>> from zeroos.core0 import client
>>> cl = client.Client(host='10.242.46.247')
```

But actually this won't work as the JWT should be passed together with the command.

The proper command at the moment would had been 

```
>>> from zeroos.core0 import client
>>> cl = client.Client(host='10.242.46.247', JWT)
```

**Comment by islamTaha12** [comment]
https://github.com/zero-os/0-core#using-the-python-client
