### ISSUE TITLE
disk.list stops working if your machine has loads of disks

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-core#509]
```
In [5]: result = c.raw('disk.list', {}).get()

In [6]: result
Out[6]:
STATE: 500 ERROR
STDOUT:

STDERR:

DATA:
"invalid character ']' after top-level value"

```

**Comment by muhamadazmy** [comment]
As per quick call the isssue is as following:
- we internally use `lsblk` to list the disks 
- if you have lots of disks, this produces a huge output
- Internally for memory protection we don't buffer (and send) the full output of the command but only the last `100` lines of output (plus another 100 for stderr)
- Previously we kept a 1000 lines for each, but we reduced the number to 100 to save memory.

We can have a quick fix, just by increasing the buffer size back to 1000, and then have a good fix where we can control if we need to capture full output for short running commands. I will have to take a look to see if a good fix can be done quickly.
