### ISSUE TITLE
Need a filter option on the log subscribe method

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-core#512]
@muhamadazmy please add some specs here

**Comment by muhamadazmy** [comment]
- Clients can call subscribe with a set of 'log levels' that defines the message levels they need to subscribe too.
- levels are defined here https://github.com/zero-os/0-core/blob/master/docs/monitoring/logging.md#log-levels
- Once subscribed, other calls to subscribe with the same arguments is ignored, unless given a different set of arguments, it returns an error.
