### ISSUE TITLE
missing binaries in 0-OS

### ISSUE THREAD

**Issue by delandtj** [zero-os/0-core#529]
a few things, mainly to get better openvswitch configurability
  - `ovs-appctl`
  - `tc` from the iproute2 binaries

**Comment by zaibon** [comment]
This probably  need to be moved into https://github.com/zero-os/0-initramfs or is 
@maxux you handle it ?

**Comment by muhamadazmy** [comment]
@chrisvdg ovs-appctl i think it's already part of the ovs container (i will have to check) but to make it accessible we will have to add a proxy script to it like what we do with `ovs-vsctl`

**Comment by chrisvdg** [comment]
@muhamadazmy , tagged the wrong Chris?

**Comment by muhamadazmy** [comment]
@maxux the `tc` util should be added by initramfs though

**Comment by maxux** [comment]
@muhamadazmy It's part of iproute2, it's not there already ?
