### ISSUE TITLE
Upgrade OpenVSwitch to 2.8.X

### ISSUE THREAD

**Issue by delandtj** [zero-os/0-core#530]
for better performance and a future DPDK, please upgrade openvswitch to 2.8.2

**Comment by zaibon** [comment]
This probably  need to be moved into https://github.com/zero-os/0-initramfs
@maxux you handle it ?

**Comment by delandtj** [comment]
oops... indeed

**Comment by muhamadazmy** [comment]
This should be moved to orchestrator here https://github.com/zero-os/0-orchestrator/blob/master/buildscripts/builder-ovs.sh
