### ISSUE TITLE
Change nft.open_port behavior

### ISSUE THREAD

**Issue by serboctor** [zero-os/0-core#546]
nft.open_port crashes if the port is already open. This should be noop if the port is open, otherwise we are going to have a lot of repetitive code every where listing the ports and processing the strings before opening a port.

**Comment by zaibon** [comment]
we dealt with it in the SAL: https://github.com/Jumpscale/lib9/commit/a8ba4bce8dad9158647d248994d36dd014df468f
I think behavior of the core command are ok, we can deal with it on the layer above like we did
