### ISSUE TITLE
Add primitives to set MTU on network interface

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-core#556]
In the template that configure the storage network of 0-os node. there are some line like:
```python
node.client.system('ip link set dev {} mtu 2000'.format(interface)).get()
```
We need to turned this into primitives

**Comment by zaibon** [comment]
Seems the primitives are already part of the OVS plugin container (https://github.com/zero-os/openvswitch-plugin/blob/master/plugin.toml)
So we need to properly wrap them into the 0-os SAL in js9

**Comment by muhamadazmy** [comment]
@zaibon I see the code above sets the MTU on the `node` not in the ovs container ?! I think this should be implemented on the zos node, not inside ovs container, right ?

**Comment by grimpy** [comment]
I think the original title still stands we need a way to set mtu I would suggest `client.ip.link.set_mtu(linkname, mtu)`
