### ISSUE TITLE
Add primitives for hdparm (and it's binary) for spinning down/waking up a disk

### ISSUE THREAD

**Issue by delandtj** [zero-os/0-core#573]
Power consumption is important, disks that are not in use should be spinned down, removing 8 Watts per disk.

```
hdparm -S 1 /dev/$disk # will put it to sleep in 5 seconds
hdparm -C /dev/$disk # showns it's state

```

**Comment by maxux** [comment]
`hdparm` is enabled via `busybox` and option `-S1` was tested.
