### ISSUE TITLE
Implement logic of fscache disk selection in 0-core

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-core#579]
In order to be able to have 0-robot as a primitive, we need to have the logic to select a disk for 0-fs cache in the 0-core itself, so when the node boots, it can already select a disk before booting the 0-robot container.

**Comment by muhamadazmy** [comment]
Fixed on `development` branch

**Comment by zaibon** [comment]
need to modify the scrip to be compatible with the code of the Zero-OS SAL in jumpscale
