### ISSUE TITLE
KVM migration uses incorrect sequence

### ISSUE THREAD

**Issue by serboctor** [zero-os/0-core#602]
the prepareMigrationTarget in the kvm manager, generates a new sequence and uses it to prepare the networking on the target host which means once the domain is migrated, the networking(mac address and ip) on the host wont match the values in the domain's xml.

https://github.com/zero-os/0-core/blob/master/apps/core0/subsys/kvm/manager.go#L938

**Comment by muhamadazmy** [comment]
The migration requirements are not clear atm, I checked with @grimpy  and we don't need this now. The entire migration process is probably gonna need a review. I will move this to roadmap instead.
