### ISSUE TITLE
0-core different running modes

### ISSUE THREAD

**Issue by muhamadazmy** [zero-os/0-core#607]
## Running modes:

- **debug**: redis listening on all ports (respecting organisation flag)
- **zerotier**: redis only listening on zerotier network (respecting organisation flag)
- **production** _default_: local only redis, start the bot

## Kernel params
- **debug**: set core0 log level to debug.
- **zerotier**: sets the zerotier network ID.
- **development**: start redis proxy, otherwise only accept connection from local host (for example zrobot) and in this setup, zrobot would be the only mean of communication

combining one or two of those flags we basically can have the system running in many states.
- debug: `development` or `development zerotier=<network-id>` the later case will only accept connection from zt.
- production: `-no flags-` or `zerotier=<network-id>` 

## Startup service condition
it's required now to control what service to start on boot. We need to introduce a `condition` attribute on a startup service. Where we can set a condition that control if the service should start or not. If condition attribute is not set, the service should start by default.

### condition attribute syntax
```
condition = 'expression'

expression := and(expression, expression)
expression := or(expression, expression)
expression := not(expression)
expression := kernel-param
```

**Comment by zaibon** [comment]
#609
