### ISSUE TITLE
auto mount of the 0-fs cache is not working anymore

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-core#614]
After the last update of the kernel, the [auto mount script for the 0-fs cache](https://github.com/zero-os/0-core/blob/master/tools/ensurecache.sh) is not working anymore.

Seems btrfs module is not yet mounted when the script is called.

Also the script now create a new btrfs filesystem on a new disk at each boot.
This is supposely due to the fact that any already exising btrfs filesystem with the label `sp_zos-cache` can't be mounted by the script, which trigger a preparation of another disk

**Comment by zaibon** [comment]
solved by makeing sure btrfs module is always loaded (builtin) : https://github.com/zero-os/0-initramfs/commit/d9e06604187c3c7678b583081815e41ae1d228de

**Comment by delandtj** [comment]
meh... the modules loading should happen the earliest in the boot process, so for me that's a bug, making it a builtin is a kludge
