### ISSUE TITLE
Change the Internet Reachable URL endpoint

### ISSUE THREAD

**Issue by maxux** [zero-os/0-core#621]
We need to discuss about the URL we use to test internet reachability.

The current bootstrap receive more than 10 `GET /` per seconds constantly.
At least we need to set a more precise endpoint and not get `/` but maybe we need to go back to google.com ?

**Comment by zaibon** [comment]
Can't we use public DNS server ? 8.8.8.8, 1.1.1.1 ?

**Comment by zaibon** [comment]
Can't we use public DNS server ? `8.8.8.8`, `1.1.1.1` ?

**Comment by maxux** [comment]
You talk about ping ?

**Comment by zaibon** [comment]
Not talking about protocol at all. Just that there are plenty of public server we can use to check if we can reach internet.

And if you need to use http, `1.1.1.1` is listening on port 80, so this is still a valid option

**Comment by maxux** [comment]
True, I would go for `1.1.1.1` then :)

**Comment by muhamadazmy** [comment]
I don't seem to be able to reach 1.1.1.1 ! any idea ?
