### ISSUE TITLE
Add delay when respawning container

### ISSUE THREAD

**Issue by maxux** [zero-os/0-core#644]
When a container needs to be restarted, core0 does it directly.
When the container crash at start for any reason, core0 will be busy to respawn the process more than 1000 times per seconde which basicly kills logs and performance.

We need to add a configurable way to add some cooldown between restart, and for sure not having infinite loop like this.

**Comment by muhamadazmy** [comment]
As explained on telegram, a service that is marked protected respawns immediately when it dies. Basically a protected service is a service that is crucial for system operation (redis, libvirt and others) and it means the service MUST not stay dead, not give up on it.

This is why all protected services will be respawn immediately when they die. We of course can add a delay between the retries to make it easier on the system.
