### ISSUE TITLE
Add rtinfo primitive and helper

### ISSUE THREAD

**Issue by maxux** [zero-os/0-core#655]
It would be cool to be able to set a remote host/port to reach an rtinfo server, to send directly node monitoring as soon as the node is up and running.

It would be also interesting to allows user to set another endpoint where owner could host a dashboard and see node cluster status in realtime.

Related to https://github.com/zero-os/0-initramfs/issues/85
Repository for rtinfo: https://github.com/maxux/rtinfo

**Comment by muhamadazmy** [comment]
@maxux how important is this, is this required or just a 'cool' thing to have?

**Comment by zaibon** [comment]
I think this will be really useful when we deploy the big archive later next month. to have real time data available and have tool to build nice dashbaords

**Comment by maxux** [comment]
This is not high priority, we can always start rtinfo client manually now,
since it's there anyway.

But that will be useful to have it automatically out of the box without the
need to connect a client, to know the health of the node.

And yes, that will be used a lot for the big archive cluster.
