### ISSUE TITLE
Node IP address in ZeroTier network is not listed in Zero-os console

### ISSUE THREAD

**Issue by katia-e** [zero-os/0-core#680]
This problem occurs only when running from development of Zero-os. 
Expect to have IP address of the node in ZeroTier network in the console.
IP address listed in the console now doesn't match ip in ZeroTier network.

![image](https://user-images.githubusercontent.com/32639869/40546533-cf745ad8-602f-11e8-931f-e2dc54a30219.png)

**Comment by muhamadazmy** [comment]
I think i know the reason, it's a regression bug i caused when i was trying to remove the vm tap/tun devices. I will fix it now
