### ISSUE TITLE
Cpu & memory limitation for containers

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-core#688]
The ability to limit
- the amount of memory which is addressable for processes running inside a container
- which cpu-cores processes in a container can use

**Comment by muhamadazmy** [comment]
@FastGeert I think the best way to accomplish this is that we separate cgroups mgmt from containers creation. 

## For example:
- You create the cgroups u need (and configure them) via a yet to be implemented API.
- Pass the set of cgroups that you want to be applied to the container on creation (can also be modified for running containers)

If u pass the memory/cpu limitation on creation it will not be adjustable without restarting the container, also we will end up with many cgroups that might have the same set of limitations.

Feedback?

**Comment by FastGeert** [comment]
Yes, indeed. Good analysis!
