### ISSUE TITLE
Allow passing zerotier identity in the kernel args of zeroos

### ISSUE THREAD

**Issue by serboctor** [zero-os/0-core#689]

**Comment by zaibon** [comment]
I guess this is for the 0-OS VM. Since we have this config support thingy in 0-OS that let use write file into the filesystem of a VM, can't we use this to configure the zt identity instead of adding this feature to 0-OS itself ?

**Comment by muhamadazmy** [comment]
@zaibon yes, it is. But i will add the feature anyway, because the machine will regenerate an ID on boot regardless and will override what u place.

**Comment by grimpy** [comment]
@zaibon I thought about that but that's not possible with the current flist see https://hub.gig.tech/gig-bootable/zero-os-bootable.flist.md
Using this config it would just write it in the temperary flist fs before it execute the zero-os kernel which creates a new root filesystem (which won't have that file).
