### ISSUE TITLE
Include seektime tool to improve SSD/HDD detection

### ISSUE THREAD

**Issue by maxux** [zero-os/0-core#691]
We hit some problem when using specific hardware, like RAID Controller, which fake disk capabilities. The kernel knows nothing real about the physical disk, since it's hidden by the controller. One of theses hidden thing are the `rotational` parameter, that we use to know if disk is `SSD` or `HDD`.

This result by fake HDD positive detection on 0-OS and report are wrong (eg: no SSD detected).

Since there are lot of hardware and lot of different things to support, support them one by one will be complicated. We don't really need more than the `rotational` flag for now.

I've made a small tool which **estimate** the seektime of a disk. Based on this value, this tool can **guess** if it's a `SSD` or `HDD` kind of device. Of course this is not fully accurate but it's still a better generic way to know if machine have SSD or not.

The way how core0 should implement this need to be discussed. The tool itself take a very short time to detect SSD but for HDD it takes ~1 second per disk (this is quite needed to have accurate results).

**Comment by GlenDC** [comment]
@muhamadazmy why is this closed without any comment to tell why it is closed, nor a commit/PR message that supposedly resolved it if it has been resolved at all.
