### ISSUE TITLE
Cannot boot zero-os on Virtual Box

### ISSUE THREAD

**Issue by nbabenko** [zero-os/0-core#698]
The goal was to boot Zero-os on Virtual Box and register as a farm.

![virtualbox_farm_test_27_06_2018_14_18_59](https://user-images.githubusercontent.com/4426772/41973399-29aeac7a-7a15-11e8-9c5f-1f849d8057eb.png)

After booting virtual box, cannot find machine in capacity list: 
https://capacity.threefoldtoken.com/?cru=0&mru=0&hru=0&sru=0&country=&farmer=babenkofarm

Log screen shows this:

![virtualbox_farm_test_27_06_2018_13_24_45](https://user-images.githubusercontent.com/4426772/41972414-1a003256-7a12-11e8-8e8e-a2c4dca0b9f6.png)

Please advice if I can get more extensive logs if this is not sufficient

**Comment by zaibon** [comment]
can you please give some information. Dumping an half truncated screenshot doesn't give any valuable information.

**Comment by nbabenko** [comment]
@zaibon , added more details. Please let me know if I can get somehow more detailed log / somehow get log file from it.

**Comment by zaibon** [comment]
your screenshot of the logs doesn't really show anything, can you have more complete one (in text format and not images if possible)
