### ISSUE TITLE
Setting hostname on container creation

### ISSUE THREAD

**Issue by amoljimber** [zero-os/0-core#723]
Setting the hostname of a container upon creation would be a useful feature for us.

**Comment by xmonader** [comment]
Do you mean from the Go API or python client or are you using https://github.com/threefoldtech/zos to create containers?

**Comment by zaibon** [comment]
0-core API already allow you to set the hostname of a container when you create it.

**Comment by amoljimber** [comment]
I use the python api

**Comment by muhamadazmy** [comment]
All new fixes and development has been moved to https://github.com/threefoldtech/0-core

**Comment by zaibon** [comment]
@amoljimber : https://github.com/threefoldtech/jumpscale_lib/blob/development/JumpscaleLib/sal_zos/container/Container.py#L32

**Comment by amoljimber** [comment]
Oh well I guess I oversaw it. Thanks for the help!
Issue may be closed.
