### ISSUE TITLE
info.nic command doesn't report all the flag of the network interface

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-core#724]
we need to be able to detect cable failure and these sort of event. 
Currently the `info.nic` command only report these flags: `up`,`broadcast`,`loopback`,`pointtopoint`,`multicast`

We need the full list of flag return by the kernel. not just a subset.

**Comment by delandtj** [comment]
For now, I'm going to just expose in `info.nic` also
  - `carrier` as bool
  - `operstate` as bool

**Comment by zaibon** [comment]
@delandtj sounds good.
just `info.nic()` returns a dict not an object so the API would more look like
```python
info = node.client.info.nic()
if info['carrier']:
   ...
if info['operstate']:
   ....
```

**Comment by zaibon** [comment]
moved to https://github.com/threefoldtech/0-core/issues/100
